title: "[Datacenter/Server] Your Character Name"
body:
- type: textares
  attributes:
    label: Image
    description: Add an image of your character.
  validations:
    required: true
- type: input
  attributes:
    label: Character Name
    description: The first and last name of your character.
  validations:
    required: true
- type: dropdown
  attributes:
    label: Data Center
    description: What data center is this character in?
    multiple: false
    options:
      - Aether
      - Crystal
      - Dynamis
      - Primal
  validations:
    required: true
- type: dropdown
  attributes:
    label: Server
    description: What server is this character in?
    multiple: false
    options:
      - Adamantoise
      - Balmung
      - Behemonth
      - Brynhildr
      - Cactuar
      - Coeurl
      - Diabolos
      - Excalibur
      - Exodus
      - Faerie
      - Famfrit
      - Gilgamesh
      - Goblin
      - Halicarnassus
      - Hyperion
      - Jenova
      - Lamia
      - Leviathan
      - Maduin
      - Malboro
      - Marilith
      - Mateus
      - Midgardsomr
      - seraph
      - Siren
      - Ultros
      - Zalera
  validations:
    required: true
- type: input
  attributes:
    label: Race
    description: What race is your character?
  validations:
    required: true
- type: input
  attributes:
    label: Clan
    description: What clan is your character?
  validations:
    required: false
- type: input
  attributes:
    label: Gender
    description: What gender is your character
  validations:
    required: true
- type: input
  attributes:
    label: Pronouns
    description: What pronouns does your character use?
  validations:
    required: true
- type: input
  attributes:
    label: Age
    description: How old in your character?
  validations:
    required: false
- type: input
  attributes:
    label: Occupation
    description: What occupation or job does your character have?
  validations:
    required: false
- type: textarea
  attributes:
    label: Description
    description: A description of your character or any blurb you would like to share.
  validations:
    required: true
- type: textarea
  attributes:
    label: Hooks
    description: Any hooks for your character that you would like to share.
  validations:
    required: false
- type: input
  attributes:
    label: Carrd/Link
    description: Carrd, Character page or any relevant link.
  validations:
    required: false
- type: textarea
  attributes:
    label: Types of Roleplay
    description: The types of roleplay you are interested in doing with this character.
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Contact
    description: Are you okay with being contacted?
    options:
      - label: I am open to and would like others to contact me.
- type: textarea
  attributes:
    label: Contact Details
    description: The best ways to contact you.
  validations: